import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { IndexAbout } from "../Components/Index/About";
import { Peaky } from "../Components/PeakyBlinders";
import styles from "../styles/Home.module.css";
import indeStyle from "../styles/indexStyle.module.scss";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} ${indeStyle.main}`}>
        <IndexAbout />
        <Peaky />
      </main>
    </div>
  );
};

export default Home;
